name: Build windows release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: setup python
      uses: actions/setup-python@v3
      with:
          python-version: "3.10"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

    - name: Build
      env:
          PYTHONPATH: "${{ github.workspace }};${{ github.workspace }}\\src;${{ github.workspace }}\\tests"
      run: python pyinstaller.py

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        path: dist/ps2mc-browser.exe
